workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS Release
        script: |
          flutter build ios --release --no-codesign
      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app chatw.app
          cp -r chatw.app Payload/
          zip -r chatw.ipa Payload
          mv chatw.ipa ../../../
    artifacts:
      - "*.ipa"
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
